// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/service.proto

package mongodbtest

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{0}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type ReadRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadRequest) Reset()         { *m = ReadRequest{} }
func (m *ReadRequest) String() string { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()    {}
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{1}
}

func (m *ReadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadRequest.Unmarshal(m, b)
}
func (m *ReadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadRequest.Marshal(b, m, deterministic)
}
func (m *ReadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadRequest.Merge(m, src)
}
func (m *ReadRequest) XXX_Size() int {
	return xxx_messageInfo_ReadRequest.Size(m)
}
func (m *ReadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadRequest proto.InternalMessageInfo

func (m *ReadRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type UpdateRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{2}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UpdateRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UserResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserResponse) Reset()         { *m = UserResponse{} }
func (m *UserResponse) String() string { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()    {}
func (*UserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{3}
}

func (m *UserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResponse.Unmarshal(m, b)
}
func (m *UserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResponse.Marshal(b, m, deterministic)
}
func (m *UserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResponse.Merge(m, src)
}
func (m *UserResponse) XXX_Size() int {
	return xxx_messageInfo_UserResponse.Size(m)
}
func (m *UserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserResponse proto.InternalMessageInfo

func (m *UserResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UserResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserResponse) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type ReadAllResponse struct {
	Users                []*UserResponse `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ReadAllResponse) Reset()         { *m = ReadAllResponse{} }
func (m *ReadAllResponse) String() string { return proto.CompactTextString(m) }
func (*ReadAllResponse) ProtoMessage()    {}
func (*ReadAllResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{4}
}

func (m *ReadAllResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadAllResponse.Unmarshal(m, b)
}
func (m *ReadAllResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadAllResponse.Marshal(b, m, deterministic)
}
func (m *ReadAllResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadAllResponse.Merge(m, src)
}
func (m *ReadAllResponse) XXX_Size() int {
	return xxx_messageInfo_ReadAllResponse.Size(m)
}
func (m *ReadAllResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadAllResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadAllResponse proto.InternalMessageInfo

func (m *ReadAllResponse) GetUsers() []*UserResponse {
	if m != nil {
		return m.Users
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateRequest)(nil), "pb.CreateRequest")
	proto.RegisterType((*ReadRequest)(nil), "pb.ReadRequest")
	proto.RegisterType((*UpdateRequest)(nil), "pb.UpdateRequest")
	proto.RegisterType((*UserResponse)(nil), "pb.UserResponse")
	proto.RegisterType((*ReadAllResponse)(nil), "pb.ReadAllResponse")
}

func init() {
	proto.RegisterFile("proto/service.proto", fileDescriptor_c33392ef2c1961ba)
}

var fileDescriptor_c33392ef2c1961ba = []byte{
	// 333 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x52, 0x4b, 0x4f, 0xf3, 0x30,
	0x10, 0x54, 0xd3, 0x36, 0xdf, 0xc7, 0xf6, 0x05, 0x2e, 0x42, 0x51, 0x10, 0x52, 0xd5, 0x03, 0x2a,
	0x87, 0x26, 0xa2, 0x48, 0x48, 0x1c, 0x79, 0x1d, 0xb9, 0x44, 0xea, 0x85, 0x9b, 0x83, 0x97, 0x28,
	0x52, 0x12, 0x1b, 0xdb, 0x05, 0x71, 0xe4, 0x9f, 0x23, 0xdb, 0x6d, 0x95, 0xbe, 0x8e, 0xdc, 0xb2,
	0xbb, 0xe3, 0x99, 0xc9, 0xec, 0xc2, 0x50, 0x48, 0xae, 0x79, 0xac, 0x50, 0x7e, 0xe6, 0x6f, 0x18,
	0xd9, 0x8a, 0x78, 0x22, 0x0d, 0xcf, 0x33, 0xce, 0xb3, 0x02, 0x63, 0xdb, 0x49, 0x17, 0xef, 0x31,
	0x96, 0x42, 0x7f, 0x3b, 0xc0, 0x78, 0x0e, 0xbd, 0x47, 0x89, 0x54, 0x63, 0x82, 0x1f, 0x0b, 0x54,
	0x9a, 0x10, 0x68, 0x55, 0xb4, 0xc4, 0xa0, 0x31, 0x6a, 0x4c, 0x8e, 0x12, 0xfb, 0x4d, 0x4e, 0xa1,
	0x8d, 0x25, 0xcd, 0x8b, 0xc0, 0xb3, 0x4d, 0x57, 0x90, 0x10, 0xfe, 0x0b, 0xaa, 0xd4, 0x17, 0x97,
	0x2c, 0x68, 0xda, 0xc1, 0xba, 0x1e, 0x5f, 0x40, 0x27, 0x41, 0xca, 0x56, 0xa4, 0x7d, 0xf0, 0x72,
	0xb6, 0xa4, 0xf4, 0x72, 0x36, 0x46, 0xe8, 0xcd, 0x05, 0xab, 0xa9, 0x6e, 0x01, 0xd6, 0x2e, 0xbc,
	0x7d, 0x2e, 0x9a, 0x87, 0x5c, 0xb4, 0xb6, 0x5c, 0x30, 0xe8, 0xce, 0x15, 0xca, 0x04, 0x95, 0xe0,
	0x95, 0xc2, 0x3f, 0x52, 0xb9, 0x83, 0x81, 0xf9, 0xd7, 0xfb, 0xa2, 0x58, 0x0b, 0x5d, 0x42, 0x7b,
	0xa1, 0x50, 0xaa, 0xa0, 0x31, 0x6a, 0x4e, 0x3a, 0xb3, 0xe3, 0x48, 0xa4, 0x51, 0xdd, 0x49, 0xe2,
	0xc6, 0xb3, 0x1f, 0x0f, 0x3a, 0xa6, 0xff, 0x42, 0x2b, 0x9a, 0xa1, 0x24, 0x53, 0xf0, 0xdd, 0x36,
	0xc8, 0x89, 0x79, 0xb2, 0xb1, 0x99, 0x70, 0x87, 0x85, 0x5c, 0x41, 0xcb, 0x28, 0x93, 0x81, 0x99,
	0xd4, 0xf2, 0xde, 0x03, 0x9d, 0x82, 0xef, 0x12, 0x77, 0xcc, 0x1b, 0xe9, 0xef, 0x81, 0x5f, 0x83,
	0xff, 0x84, 0x05, 0x6a, 0xdc, 0xe5, 0x3e, 0x8b, 0xdc, 0x3d, 0x45, 0xab, 0x7b, 0x8a, 0x9e, 0xcd,
	0x3d, 0x91, 0x5b, 0xf8, 0xb7, 0x8c, 0x81, 0x1c, 0x80, 0x84, 0xc3, 0x15, 0x57, 0x2d, 0xab, 0x87,
	0xfe, 0x6b, 0x37, 0x2e, 0x79, 0x95, 0x71, 0x96, 0x6a, 0x54, 0x3a, 0xf5, 0xed, 0xa3, 0x9b, 0xdf,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x79, 0xb6, 0x2a, 0xc4, 0xd0, 0x02, 0x00, 0x00,
}
